{"cve": {"id": "CVE-2024-8041", "sourceIdentifier": "cve@gitlab.com", "published": "2024-08-22T16:15:10.880", "lastModified": "2024-08-22T16:15:10.880", "vulnStatus": "Received", "cveTags": [], "descriptions": [{"lang": "en", "value": "A Denial of Service (DoS) issue has been discovered in GitLab CE/EE affecting all versions prior to 17.1.6, 17.2 prior to 17.2.4, and 17.3 prior to 17.3.1. A denial of service could occur upon importing a maliciously crafted repository using the GitHub importer."}], "metrics": {"cvssMetricV31": [{"source": "cve@gitlab.com", "type": "Secondary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 6.5, "baseSeverity": "MEDIUM"}, "exploitabilityScore": 2.8, "impactScore": 3.6}]}, "weaknesses": [{"source": "cve@gitlab.com", "type": "Secondary", "description": [{"lang": "en", "value": "CWE-400"}]}], "references": [{"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/463092", "source": "cve@gitlab.com"}, {"url": "https://hackerone.com/reports/2499070", "source": "cve@gitlab.com"}]}}