{"cve": {"id": "CVE-2024-0793", "sourceIdentifier": "secalert@redhat.com", "published": "2024-11-17T11:15:06.340", "lastModified": "2024-11-17T11:15:06.340", "vulnStatus": "Received", "cveTags": [], "descriptions": [{"lang": "en", "value": "A flaw was found in kube-controller-manager. This issue occurs when the initial application of a HPA config YAML lacking a .spec.behavior.scaleUp block causes a denial of service due to KCM pods going into restart churn."}], "metrics": {"cvssMetricV31": [{"source": "secalert@redhat.com", "type": "Primary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:H", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "CHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 7.7, "baseSeverity": "HIGH"}, "exploitabilityScore": 3.1, "impactScore": 4.0}]}, "weaknesses": [{"source": "secalert@redhat.com", "type": "Primary", "description": [{"lang": "en", "value": "CWE-20"}]}], "references": [{"url": "https://access.redhat.com/errata/RHSA-2024:0741", "source": "secalert@redhat.com"}, {"url": "https://access.redhat.com/errata/RHSA-2024:1267", "source": "secalert@redhat.com"}, {"url": "https://access.redhat.com/security/cve/CVE-2024-0793", "source": "secalert@redhat.com"}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2214402", "source": "secalert@redhat.com"}, {"url": "https://github.com/openshift/kubernetes/pull/1876", "source": "secalert@redhat.com"}]}}