{"cve": {"id": "CVE-2024-35328", "sourceIdentifier": "cve@mitre.org", "published": "2024-06-13T16:15:11.037", "lastModified": "2024-08-28T15:15:16.750", "vulnStatus": "Modified", "cveTags": [{"sourceIdentifier": "cve@mitre.org", "tags": ["disputed"]}], "descriptions": [{"lang": "en", "value": "libyaml v0.2.5 is vulnerable to a denial of service. Affected by this issue is the function yaml_parser_parse of the file /src/libyaml/src/parser.c. NOTE: this is disputed by the supplier because the discoverer's sample C code is incorrect: it does not call required _initialize functions that are described in the LibYAML documentation."}, {"lang": "es", "value": "libyaml v0.2.5 es vulnerable a DDOS. La funci\u00f3n yaml_parser_parse del archivo /src/libyaml/src/parser.c es afectada por esta vulnerabilidad."}], "metrics": {"cvssMetricV31": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 7.5, "baseSeverity": "HIGH"}, "exploitabilityScore": 3.9, "impactScore": 3.6}]}, "weaknesses": [{"source": "nvd@nist.gov", "type": "Primary", "description": [{"lang": "en", "value": "CWE-835"}]}], "configurations": [{"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:pyyaml:libyaml:0.2.5:*:*:*:*:*:*:*", "matchCriteriaId": "A6BEAEF3-43E6-4FD6-8A52-C73530C631E9"}]}]}], "references": [{"url": "https://github.com/idhyt/pocs/blob/main/libyaml/CVE-2024-35328.c", "source": "cve@mitre.org", "tags": ["Exploit"]}, {"url": "https://github.com/idhyt/pocs/tree/main/libyaml", "source": "cve@mitre.org"}]}}