{"cve": {"id": "CVE-2024-50202", "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67", "published": "2024-11-08T06:15:16.723", "lastModified": "2024-11-08T19:01:03.880", "vulnStatus": "Awaiting Analysis", "cveTags": [], "descriptions": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nnilfs2: propagate directory read errors from nilfs_find_entry()\n\nSyzbot reported that a task hang occurs in vcs_open() during a fuzzing\ntest for nilfs2.\n\nThe root cause of this problem is that in nilfs_find_entry(), which\nsearches for directory entries, ignores errors when loading a directory\npage/folio via nilfs_get_folio() fails.\n\nIf the filesystem images is corrupted, and the i_size of the directory\ninode is large, and the directory page/folio is successfully read but\nfails the sanity check, for example when it is zero-filled,\nnilfs_check_folio() may continue to spit out error messages in bursts.\n\nFix this issue by propagating the error to the callers when loading a\npage/folio fails in nilfs_find_entry().\n\nThe current interface of nilfs_find_entry() and its callers is outdated\nand cannot propagate error codes such as -EIO and -ENOMEM returned via\nnilfs_find_entry(), so fix it together."}, {"lang": "es", "value": "En el kernel de Linux, se ha resuelto la siguiente vulnerabilidad: nilfs2: propagar errores de lectura de directorio desde nilfs_find_entry() Syzbot inform\u00f3 que se produce un bloqueo de tarea en vcs_open() durante una prueba de fuzzing para nilfs2. La causa ra\u00edz de este problema es que en nilfs_find_entry(), que busca entradas de directorio, ignora los errores cuando falla la carga de una p\u00e1gina/folio de directorio a trav\u00e9s de nilfs_get_folio(). Si las im\u00e1genes del sistema de archivos est\u00e1n da\u00f1adas, y el i_size del inodo del directorio es grande, y la p\u00e1gina/folio del directorio se lee correctamente pero falla la comprobaci\u00f3n de cordura, por ejemplo, cuando est\u00e1 llena de ceros, nilfs_check_folio() puede seguir arrojando mensajes de error en r\u00e1fagas. Solucione este problema propagando el error a los llamadores cuando falla la carga de una p\u00e1gina/folio en nilfs_find_entry(). La interfaz actual de nilfs_find_entry() y sus llamadores est\u00e1 desactualizada y no puede propagar c\u00f3digos de error como -EIO y -ENOMEM devueltos a trav\u00e9s de nilfs_find_entry(), as\u00ed que arr\u00e9glenlo juntos."}], "metrics": {}, "references": [{"url": "https://git.kernel.org/stable/c/08cfa12adf888db98879dbd735bc741360a34168", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/270a6f9df35fa2aea01ec23770dc9b3fc9a12989", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/9698088ac7704e260f492d9c254e29ed7dd8729a", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/b4b3dc9e7e604be98a222e9f941f5e93798ca475", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/bb857ae1efd3138c653239ed1e7aef14e1242c81", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/c1d0476885d708a932980b0f28cd90d9bd71db39", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/edf8146057264191d5bfe5b91773f13d936dadd3", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/efa810b15a25531cbc2f527330947b9fe16916e7", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}]}}